import type { ReactNode } from 'react'
import AlertsPanel from '../../src/components/AlertsPanel'
import type { Alert } from '../../src/lib/analytics'

// Ported from the real message shape generated by generateAlerts() in
// src/lib/analytics.ts — congestion alerts driven by trailers idle >24h at a site.
//
// AlertsPanel sits directly on the dashboard page body with no wrapper of its
// own (src/pages/Dashboard.tsx) and its accent colors (bg-red-950/20,
// text-red-300, etc.) are tuned for the app's actual default theme — dark,
// near-black page background (`savedTheme || 'dark'` in Sidebar.tsx; `.dark
// body { background-color: #08080a }` in tailwind.css). On a plain white
// canvas those colors read as washed-out/low-contrast, which is not how the
// component is ever actually seen. This wrapper reproduces the real page
// backdrop it's always composed against — it does not modify AlertsPanel.
function DarkPageBackdrop({ children }: { children: ReactNode }) {
  return (
    <div className="dark" style={{ background: '#08080a', padding: '1.5rem' }}>
      {children}
    </div>
  )
}

export function SingleMedium() {
  const alerts: Alert[] = [
    { id: 'congestion-0', severity: 'medium', message: '2 trailers idle >24h at Marina Gate Towers — site may be bottlenecked, consider rerouting the next dispatches.' },
  ]
  return <DarkPageBackdrop><AlertsPanel alerts={alerts} /></DarkPageBackdrop>
}

export function MultipleMixedSeverity() {
  const alerts: Alert[] = [
    { id: 'congestion-0', severity: 'high', message: '4 trailers idle >24h at Al Qudra Villas — site may be bottlenecked, consider rerouting the next dispatches.' },
    { id: 'congestion-1', severity: 'medium', message: '1 trailer idle >24h at Marina Gate Towers — site may be bottlenecked, consider rerouting the next dispatches.' },
  ]
  return <DarkPageBackdrop><AlertsPanel alerts={alerts} /></DarkPageBackdrop>
}

export function AllHighSeverity() {
  const alerts: Alert[] = [
    { id: 'congestion-0', severity: 'high', message: '5 trailers idle >24h at The Acres Phase 1 — site may be bottlenecked, consider rerouting the next dispatches.' },
    { id: 'congestion-1', severity: 'high', message: '3 trailers idle >24h at Al Qudra Villas — site may be bottlenecked, consider rerouting the next dispatches.' },
  ]
  return <DarkPageBackdrop><AlertsPanel alerts={alerts} /></DarkPageBackdrop>
}
